/* Generated By:JavaCC: Do not edit this line. CharStream.java Version 5.0 */
/* JavaCCOptions:STATIC=false,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.trypticon.luceneupgrader.lucene3.internal.lucene.queryParser;

public
interface CharStream {

  char readChar() throws java.io.IOException;

  @Deprecated
  int getColumn();

  @Deprecated
  int getLine();

  int getEndColumn();

  int getEndLine();

  int getBeginColumn();

  int getBeginLine();

  void backup(int amount);

  char BeginToken() throws java.io.IOException;

  String GetImage();

  char[] GetSuffix(int len);

  void Done();

}
/* JavaCC - OriginalChecksum=6b854f7f279fcc2b052037ffc369be2d (do not edit this line) */
